[profile.default]
src = "contracts"
out = "out"
libs = ["chain/lib"]
script = "script"

remappings = [
    "forge-std/=chain/lib/forge-std/src/",
    "@openzeppelin/=chain/lib/openzeppelin-contracts/",
    "src/=contracts/"
]
